# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(default=None, to='backEnd.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='history_high',
            field=models.IntegerField(default=0),
        ),
    ]
