# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0002_auto_20180607_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(null=True, to='backEnd.User'),
        ),
    ]
